<!-- MAIN -->
<main class="main">
  <div class="container">
    <div class="page-presentation">
      <h2>Faquarium, Parc de découverte des océans</h2>
      <p>Depuis 1995,<br/><span>Faquarium</span>, membre du réseau marque Bretagne, raconte l’histoire naturelle de l’océan et accomplit une mission de médiation scientifique avec pédagogie et créativité.</p>
    </div>
    <hr class="hr-css">
    <div class="content-about">
      <div class="content-img">
        <img class="about-img" src="ressources/a-shuau-obofili-vuFzbaTpR7s-unsplash.jpg" alt="Ethique">
      </div>
      <div class="content-text">
        <h2>Ethique</h2>
        <p><span>Faquarium</span> s’engage à construire des écosystèmes durables pour reproduire quasi à l’identique l’habitat de chaque zone géographique représentée.  A partir d’un écosystème précis, de nombreuses études sur la qualité d’eau, l’habitat, la luminosité, l’alimentation ou encore la cohabitation des espèces sont réalisées en amont de la construction du bassin.</p>
        <p>Aucun animal n’est choisi pour son attrait commercial et spectaculaire. Nous optimisons les échanges, les dons et les reproductions. Notre objectif est la reproduction d’un écosystème pour sensibiliser le public.</p>
      </div>
    </div>
    <!--  -->
    <div class="content-about">
      <div class="content-img">
        <img class="about-img" src="ressources/anniversaire-feerique-aquatique.jpg" alt="Une mission pédagogique">
      </div>
      <div class="content-text">
        <h2>Une mission pédagogique</h2>
        <p>Formidable outil pédagogique, Faquarium et son équipe pédagogique proposent de faire découvrir aux élèves les mystères de la mer au travers d’une collection exceptionnelle au service d'ateliers interactifs.</p>
        <p>Grâce à la relation particulière qu’entretient l’enfant avec les animaux marins, ces ateliers permettent une véritable découverte sensorielle pour les plus petits et seront le point de départ des cours théoriques en classe pour les plus grands.</p>
        <p>C’est l’occasion idéale d’observer, de découvrir, de toucher ou encore de nourrir les animaux et de mettre en évidence les relations qui les unissent</p>
        <p>Les ateliers sont en parfaite adéquation avec les programmes scolaires et nous souhaitons que chez nous, les élèves prennent plaisir à apprendre.</p>
      </div>
    </div>
    <!--  -->
    <div class="content-about">
      <div class="content-img">
        <img class="about-img" src="ressources/manchot-papou-pygoscelis-papua-pp1oceanopolis.jpg" alt="Élevage">
      </div>
      <div class="content-text">
        <h2>Reproductions et élevages</h2>
        <p>Alliant patience et observations, expériences et connaissances, les biologistes ont obtenu de réels succès grâce aux améliorations et ajustements : de la qualité de l’eau, des éclairages, de la nourriture.</p>
        <p>Aujourd’hui, l’Aquarium reproduit une vingtaine d’espèces marines et développe avec succès la culture de différentes variétés de coraux.</p>
        <p>Poissons clown (Amphiprion clarkii) , poissons porc des Caraïbes(Anisotremus virginicus), hippocampes (Hippocampus hippocampus, Hippocampus guttulatus, Hippocampus abdominalis, espèces menacées et protégées), seiches (Sepia officinalis) et méduses cassiopée, aurélie et constellée (Cassiopea andromeda, Aurelia aurita, Phyllorhiza punctata) …, naissent régulièrement dans les quarantaines.</p>
        <p>Pour assurer le succès des reproductions et la croissance des larves de poissons, l’élevage de proies vivantes est nécessaire, (rotifères et artémia), elles sont enrichies pour avoir les qualités nutritives adaptées aux larves.</p>
      </div>
    </div>
  </div>
</main>
