<!-- MAIN -->
<main class="main">
  <div class="container" id="access-container">
    <!-- TARIFS -->
    <div class="tarif">
      <div class="acces-title">
        <h2>TARIFS 2020</h2>
        <p>Réservez selon vos envies</p>
      </div>
      <div class="content" id="tarifs">
        <!--  -->
        <div class="tarif-container">
          <div class="tarif-title">
            <a href="#tarifs"></a>
            <h3>Tarif Internet</h3>
          </div>
          <div class="tarif-img">
            <img src="ressources/white-and-gray-dolphin-on-blue-water-64219.jpg" alt="none">
          </div>
          <div class="tarif-text">
            <div class="tarif-choice">
              <div class="tarif-adult">
                <h4>Adulte</h4>
                <p class="price">14.5€</p>
              </div>
              <div class="tarif-child">
                <h4>Enfant</h4>
                <p class="price">10.5€</p>
              </div>
            </div>
            <div class="tarif-info">
              <ul>
                <li>Billet non daté (valable pendant la saison 2020 selon le calendrier d'ouverture).</li>
                <li>Billet daté à tarif réduit.</li>
                <li>Billet spécial smartphone ou imprimable.</li>
              </ul>
            </div>
          </div>
          <div class="buy">
            <div class="buy-action">
              <a href="index.php?p=reservation">
                <div><i class="fas fa-cart-plus"></i>Je réserve mon billet</div>
              </a>
            </div>
          </div>
        </div>
        <!--  -->
        <div class="tarif-container">
          <div class="tarif-title">
            <h3>Plein Tarif</h3>
          </div>
          <div class="tarif-img">
            <img src="ressources/jack-young-aw0zJL143SI-unsplash.jpg" alt="none">
          </div>
          <div class="tarif-text">
            <div class="tarif-choice">
              <div class="tarif-adult">
                <h4>Adulte</h4>
                <p class="price">16€</p>
              </div>
              <div class="tarif-child">
                <h4>Enfant</h4>
                <p class="price">12.5€</p>
              </div>
            </div>
            <div class="tarif-info">
              <ul>
                <li>Billet valable le jour de l'achat en caisse</li>
                <li>Tarif enfant : de 4 à 12 ans inclus</li>
                <li>Tarif adulte : à partir de 13 ans</li>
                <li>Gratuit pour les moins de 4 ans</li>
              </ul>
            </div>
          </div>
          <div class="buy">
            <div class="buy-action">
              <a href="index.php?p=reservation">
                <div><i class="fas fa-cart-plus"></i>Je réserve mon billet</div>
              </a>
            </div>
          </div>
        </div>
        <!--  -->
        <div class="tarif-container">
          <div class="tarif-title">
            <h3>Tarif Groupes</h3>
          </div>
          <div class="tarif-img">
            <img src="ressources/matt-helbig-wdL8UywQtWU-unsplash.jpg" alt="none">
          </div>
          <div class="tarif-text">
            <div class="tarif-choice">
              <div class="tarif-adult">
                <h4>Adulte</h4>
                <p class="price">13.5€</p>
              </div>
              <div class="tarif-child">
                <h4>Enfant</h4>
                <p class="price">9.5€</p>
              </div>
            </div>
            <div class="tarif-info">
              <ul>
                <li>Billet coupe-file</li>
                <li>Billet non daté (valable pendant la saison 2020 selon le calendrier d'ouverture).</li>
                <li>Tarif enfant : de 4 à 12 ans inclus</li>
                <li>Tarif adulte : à partir de 13 ans</li>
                <li>Gratuit pour les moins de 4 ans</li>
              </ul>
            </div>
          </div>
          <div class="buy">
            <div class="buy-action">
              <a href="index.php?p=reservation">
                <div><i class="fas fa-cart-plus"></i>Je réserve mon billet</div>
              </a>
            </div>
          </div>
        </div>
        <!--  -->
        <div class="tarif-container">
          <div class="tarif-title">
            <h3>Pass</h3>
          </div>
          <div class="tarif-img">
            <img src="ressources/two-boy-touching-aquarium-glass-3167782.jpg" alt="none">
          </div>
          <div class="tarif-text">
            <div class="tarif-choice">
              <div class="tarif-adult">
                <h4>Adulte</h4>
                <p class="price">35€</p>
              </div>
              <div class="tarif-child">
                <h4>Enfant</h4>
                <p class="price">25€</p>
              </div>
            </div>
            <div class="tarif-info">
              <ul>
                <li>Une immersion dans le monde marin pour se faire plaisir ou bien pour offrir !</li>
                <li>Personnelle et nominative, sa validité est d'1 an à compter de sa date d'activation</li>
                <li>Tarif adulte : à partir de 13 ans</li>
                <li>Pass spécial smartphone ou imprimable.</li>
              </ul>
            </div>
          </div>
          <div class="buy">
            <div class="buy-action">
              <a href="index.php?p=reservation">
                <div><i class="fas fa-cart-plus"></i>Je réserve mon pass</div>
              </a>
            </div>
          </div>
        </div>
        <!--  -->
      </div>
      <div class="content" id="soigneur-access">
        <hr class="hr-css">
        <div class="tarif-title">
          <h3>Soigneur d'un Jour</h3>
        </div>
        <div class="tarif-img">
          <img src="ressources/stingray-4392776_1920.jpg" alt="none">
        </div>
        <div class="tarif-choice">
          <div class="tarif-unique">
            <h4>Tarif Unique</h4>
            <p class="price">70€</p>
          </div>
        </div>
        <div class="tarif-info">
          <ul>
            <li>Une immersion dans le monde marin pour se faire plaisir, ou pour offrir !</li>
            <li>Durée de la demi-journée : 2h30 </li>
            <li>Les soigneurs d'un jour doivent porter une tenue adaptée pour travailler avec les animaux (bottes & vêtements confortables).</li>
            <li>Votre billet nominatif vous sera demandé à votre arrivée. Merci de vous présenter à l'entrée du Grand Aquarium au point de rendez-vous signalisé.</li>
            <li>À partir de 12 ans (accompagné d’un adulte) ou 16 ans (non accompagné)</li>
          </ul>
        </div>
        <div class="buy">
          <div class="buy-action">
            <a href="index.php?p=reservation">
              <div><i class="fas fa-cart-plus"></i>Je réserve mon Pass Soigneur</div>
            </a>
          </div>
        </div>
      </div>
    </div>
    <!-- HORAIRES  -->
    <div class="horaires">
      <div class="acces-title">
        <h2>HORAIRES 2020</h2>
        <p>Prenez votre temps au bon moment.</p>
      </div>
        <div class="calendar" id="calendar"></div>
    </div>
    <!-- ACCES -->
    <div class="access">
      <a href="#plan"></a>
      <h2>PLAN</h2>
      <p>Préparez votre voyage, et votre route !</p>
      <div id="access-iframe">
        <iframe height="600" src="https://maps.google.com/maps?width=100%&amp;height=600&amp;hl=en&amp;coord=47.4233978,-120.3118753,17&amp;q=13%20Orondo%20Ave%2C%20Wenatchee%2C%20WA%2098801%2C%20%C3%89tats-Unis+(Ila%20Yoga)&amp;ie=UTF8&amp;t=&amp;z=14&amp;iwloc=B&amp;output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"><a href="https://www.maps.ie/map-my-route/">Map a route</a>
        </iframe>
      </div>
    </div>
  </div>
  <script src="js/calendar.js"></script>
</main>
