<!-- MAIN -->
<main class="main" id="reservation-main">
  <div class="container">
    <div class="reservation-title">
      <h1>Réservation</h1>
      <p>Recevez votre réservation nominative par mail et payez aux bornes interactives pour esquiver la file !</p>
      <p>Remplissez ce formulaire :</p>
    </div>
    <form class="form" action="#" method="post">

      <div class="border-max">
        <!-- <label class="label-form" for="lastname">Nom de famille</label> -->
        <div class="control-content">
          <div class="control-form">
            <input id="input1" type="text" name="lastname" value="" placeholder="Nom de famille" required>
          </div>
        </div>
      </div>

      <div class="border-max">
        <!-- <label class="label-form" for="firstname">Prénom</label> -->
        <div class="control-content">
          <div class="control-form">
            <input id="input2" type="text" name="firstname" value="" placeholder="Prénom" required>
          </div>
        </div>
      </div>

      <div class="border-max">
        <!-- <label class="label-form" for="age">Âge</label> -->
        <div class="control-content">
          <div class="control-form">
            <select class="" name="age">
                <option value="">0 - 3 ans</option>
                <option value="">3 - 11 ans</option>
                <option value="">12 - 24 ans</option>
                <option value="">24 et plus</option>
            </select>
          </div>
        </div>
      </div>

      <div class="border-max">
        <!-- <label class="label-form" for="mail">E-mail</label> -->
        <div class="control-content">
          <div class="control-form">
            <input id="input3" type="email" name="mail" value="" placeholder="Email" required>
          </div>
        </div>
      </div>

      <button id="final-res" type="button" name="button">Réserver</button>

    </form>


  </div>
</main>
