<!-- FOOTER -->
<footer class="footer">
  <div class="flexslider">
    <div id="flexslider-title">
      <img src="ressources/faquarium_foot_logo" alt="">
    </div>
    <div class="flexslider carousel">
      <ul class="slides">
        <li>
          <img class="flex-mini" src="ressources/aurelia-aurita-pp-1.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/aurelia-aurita-pp-2.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/poisson-mandarin-slider-2-800x400.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/raie-pastenague-1.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/reproduction-poisson-clown.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/anemone-fish-1496866_1920-1024x678.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/manchot-papou-pygoscelis-papua-pp1oceanopolis.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/Nausicaa-exposition-temporaire-Ocean-et-climat-chaud-devant-Manchots-du-Cap-Spheniscus-demersus-nourrissage-copryright-Alexis-ROSENFELD-Nausicaa-diaporama-483x221.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/aurelia-aurita-pp-3.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/manchot-papou-pygoscelis-papua-pp1oceanopolis.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/reproduction-poisson-clown.jpg" alt="Image flexslider" />
        </li>
        <li>
          <img class="flex-mini" src="ressources/aurelia-aurita-pp-1.jpg" alt="Image flexslider" />
        </li>
      </ul>
    </div>
  </div>
  <div id="social">

    <div class="social-container">
      <a title="Faquarium Facebook" href="https://facebook.com"><i class="fab fa-facebook"></i></a>
    </div>

    <div class="social-container">
      <a title="Faquarium Twitter" href="https://twitter.com"><i class="fab fa-twitter"></i></a>
    </div>

    <div class="social-container">
      <a title="Faquarium Instagram" href="https://instagram.com"><i class="fab fa-instagram"></i></a>
    </div>

    <div class="social-container">
      <a title="Faquarium Youtube" href="https://youtube.com"><i class="fab fa-youtube"></i></a>
    </div>

  </div>
  <div id="foot">
    <div id="foot-menu">
      <ul>
        <li><a href="index.php?p=home">Home</a></li>
        <li><a href="index.php?p=about">À propos de nous</a></li>
        <li><a href="index.php?p=access">Accès</a></li>
        <li><a href="index.php?p=reservation">Billets</a></li>
      </ul>
    </div>
    <div id="foot-page">
      <small>Kevin Conversin . 8 La Roche 35190 TREVERIEN . conversin.k.pro@gmail.com</small>
    </div>
  </div>
  <script src="js/app.js"></script>
  <script src="js/fish_background.js"></script>
</footer>
</body>
</html>
