<!DOCTYPE html>
<html lang="fr">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Faquarium - <?= $title ?></title>
    <link rel="stylesheet" href="css/flexslider.css">
    <!-- <link rel="stylesheet" href="css/style.css"> -->
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="ressources/fontawesome/css/all.css">
    <script src="js/jquery.js"></script>
    <script src="js/jquery.flexslider-min.js"></script>
    <style>@import url('https://fonts.googleapis.com/css2?family=Dosis&display=swap');</style>
  </head>
