<body class="page">
  <!-- HEADER -->
  <header class="header">
    <div class="responsive-menu-button">
      <div class="btn-menu bars">
        <i class="fas fa-bars"></i>
      </div>
      <div class="btn-menu cross">
        <i class="fas fa-times"></i>
      </div>
    </div>
    <nav>
      <div class="header-item" id="logo">
        <a href="index.php?p=home"><img class="logo" src="ressources/faquarium_logo2.png" alt="Bienvenue sur le site de Faquarium"/></a>
      </div>
      <div class="header-item" id="div-menu">
        <ul id="menu">
          <li class="menu-item">
            <a class="menu-link" href="index.php?p=home">Accueil</a>
            <p class="after"></p>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="index.php?p=access">Votre visite</a>
            <p class="after"></p>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="index.php?p=parc">Notre parc</a>
            <p class="after"></p>
          </li>
          <li class="menu-item">
            <a class="menu-link" href="index.php?p=about">À propos</a>
            <p class="after"></p>
          </li>
        </ul>
      </div>
      <div class="header-item" id="reservation">
        <div id="reserver"><a href="index.php?p=reservation">Billets</a></div>
      </div>
    </nav>
  </header>
